# Generated by Django 3.1.1 on 2021-01-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210110_1457'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieslistuser',
            unique_together=set(),
        ),
    ]
